"""
Django settings for vulnwatch2 project.
Generated by 'django-admin startproject' using Django 5.1.1.
"""
from pathlib import Path
import os

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'dev-insecure-ONLY-FOR-LOCAL')
DEBUG = True
ALLOWED_HOSTS = []

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 3rd party
    "rest_framework",
    "django_filters",
    "corsheaders",

    # Local
    "core.apps.CoreConfig",
    "stats.apps.StatsConfig",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'vulnwatch2.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vulnwatch2.wsgi.application'

# --- Base de datos (subo timeout para evitar 'database is locked' en picos) ---
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        "OPTIONS": { "timeout": 120 },  # antes 30
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Config de servicio / rendimiento ---
RUN_DIR = os.getenv("RUN_DIR", r"C:\TMP\vulnwatch2\models\roberta-large-run")
DEVICE = os.environ.get("DEVICE", "cpu")       # pon "cuda" si tienes GPU
GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN", "")
SYNC_INTERVAL_MIN = int(os.environ.get("SYNC_INTERVAL_MIN", "5"))
EXPORT_DIR = os.environ.get("EXPORT_DIR", str((BASE_DIR / "exports").resolve()))
BIN_THRESHOLD = float(os.environ.get("BIN_THRESHOLD", "0.6"))

# Inference y lotes
MAX_LENGTH = int(os.environ.get("MAX_LENGTH", "512"))         # puedes bajar a 256 para +velocidad
INFER_BATCH_SIZE = int(os.environ.get("INFER_BATCH_SIZE", "16"))
SEED_CHUNK_SIZE = int(os.environ.get("SEED_CHUNK_SIZE", "40"))
BULK_DB_BATCH = int(os.environ.get("BULK_DB_BATCH", "256"))

# Jobs (cola)
JOBS_BATCH_SIZE = int(os.environ.get("JOBS_BATCH_SIZE", "32"))
JOBS_MAX_WAIT_MS = int(os.environ.get("JOBS_MAX_WAIT_MS", "150"))
JOBS_POST_BATCH_SLEEP_MS = int(os.environ.get("JOBS_POST_BATCH_SLEEP_MS", "5"))

# --- Límite de issues por repo (0 = sin límite) ---
MAX_ISSUES_PER_REPO = int(os.environ.get("MAX_ISSUES_PER_REPO", "100"))

# Comentarios (ya lo tenías)
MAX_COMMENTS_PER_ISSUE = os.environ.get("MAX_COMMENTS_PER_ISSUE", None)
